### ISSUE TITLE
Unable to run as a service

### ISSUE THREAD

**Issue by eduardobcastro** [thaJeztah/pgadmin4-docker#18]
```
version: "3"
services:
  pgadmin:
    image: fenglc/pgadmin4
    stdin_open: true
    tty: true
    ports:
      - "5050:5050"
```

Browser waits forever when trying to connect to localhost:5050

**Comment by eduardobcastro** [comment]
HTML contents is different when running this way and it makes Chrome hanging. Can see some differences with `curl -L localhost:5050`

**Comment by zkanda** [comment]
@eduardobcastro that's a wrong image, it should be `thajeztah/pgadmin4`

**Comment by thaJeztah** [comment]
Yes, this looks to be due to the wrong image being used; this works fine for me;

```yaml
version: "3"
services:
  pgadmin:
    image: thajeztah/pgadmin4
    ports:
      - "5050:5050"
```

closing this issue, but feel free to continue the conversation in case I missed something 😅
