### ISSUE TITLE
How to switch off debugging mode? 

### ISSUE THREAD

**Issue by stanislavt** [thaJeztah/pgadmin4-docker#7]
Hi Sebastiaan,

hope all is well.

How can I disabled SQL logs in docker container? When I open dashboard in browser, I always can see SQL like 
```
SELECT
    (SELECT count(*) FROM pg_stat_activity) AS "Total",
    (SELECT count(*) FROM pg_stat_activity WHERE state = 'active')  AS "Active",
    (SELECT count(*) FROM pg_stat_activity WHERE state = 'idle')  AS "Idle"
```
in console. 

Have a nice day!

**Comment by stanislavt** [comment]
The following code is the part of my docker-compose.yaml
```
pgadmin:
    container_name: pg4
    image: thajeztah/pgadmin4
    expose:
      - "5050"
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    links:
      - postgres:postgres.local
    environment:
      RDS_HOSTNAME: postgres.local
```
